import type { Source } from '../types';

export const sources: Source[] = [
  {
    id: 'js-weekly',
    type: 'rss',
    url: 'https://javascriptweekly.com/rss/',
    title: 'JavaScript Weekly',
  },
  {
    id: 'ts-blog',
    type: 'rss',
    url: 'https://devblogs.microsoft.com/typescript/feed/',
    title: 'TypeScript Blog',
  },
  {
    id: 'chrome-dev',
    type: 'rss',
    url: 'https://developer.chrome.com/static/blog/feed.xml',
    title: 'Chrome Developers',
  },
  { id: 'react-blog', type: 'rss', url: 'https://react.dev/feed.xml', title: 'React Blog' },
  { id: 'vercel', type: 'rss', url: 'https://vercel.com/atom', title: 'Vercel Changelog' },
  { id: 'node-weekly', type: 'rss', url: 'https://nodeweekly.com/rss/', title: 'Node Weekly' },
  { id: 'nextjs-blog', type: 'rss', url: 'https://nextjs.org/feed.xml', title: 'Next.js Blog' },
  { id: 'vue-blog', type: 'rss', url: 'https://blog.vuejs.org/feed.rss', title: 'Vue.js Blog' },
  { id: 'nuxt-blog', type: 'rss', url: 'https://nuxt.com/blog/rss.xml', title: 'Nuxt Blog' },
  { id: 'svelte-blog', type: 'rss', url: 'https://svelte.dev/blog/rss.xml', title: 'Svelte Blog' },
  { id: 'astro-blog', type: 'rss', url: 'https://astro.build/rss.xml', title: 'Astro Blog' },
  { id: 'deno-blog', type: 'rss', url: 'https://deno.com/feed', title: 'Deno Blog' },
  { id: 'github-blog', type: 'rss', url: 'https://github.blog/feed/', title: 'GitHub Blog' },
  { id: 'eslint-blog', type: 'rss', url: 'https://eslint.org/feed.xml', title: 'ESLint Blog' },
  {
    id: 'electron-blog',
    type: 'rss',
    url: 'https://www.electronjs.org/blog/rss.xml',
    title: 'Electron Blog',
  },
  {
    id: 'cloudflare-blog',
    type: 'rss',
    url: 'https://blog.cloudflare.com/rss/',
    title: 'Cloudflare Blog',
  },
  {
    id: 'netlify-blog',
    type: 'rss',
    url: 'https://www.netlify.com/community-feed.xml',
    title: 'Netlify Blog',
  },
  {
    id: 'aws-blog',
    type: 'rss',
    url: 'https://aws.amazon.com/blogs/developer/feed/',
    title: 'AWS Developer Blog',
  },
  {
    id: 'planetscale-blog',
    type: 'rss',
    url: 'https://planetscale.com/blog/rss.xml',
    title: 'PlanetScale Blog',
  },
  // inactive, nice to check every once and a while
  // { id: "remix-blog", type: "rss", url: "https://remix.run/rss.xml", title: "Remix Blog" },
  // { id: "vite-blog", type: "rss", url: "https://vitejs.dev/blog.xml", title: "Vite Blog" },
  // { id: "webpack-blog", type: "rss", url: "https://webpack.js.org/feed.xml", title: "Webpack Blog" },
  // { id: "rollup-blog", type: "rss", url: "https://rollupjs.org/feed.xml", title: "Rollup Blog" },
  // url: 'https://chakra-ui.com/blog/rss.xml',
  // https://mui.com/blog
  // https://tailwindcss.com/blog
  // https://github.blog/tag/npm/
  //github
  {
    id: 'esbuild-releases',
    type: 'github-releases',
    url: 'https://api.github.com/repos/evanw/esbuild/releases',
    title: 'esbuild Releases',
  },
  {
    id: 'bun-releases',
    type: 'github-releases',
    url: 'https://api.github.com/repos/oven-sh/bun/releases',
    title: 'Bun Releases',
  },
  {
    id: 'vercel-releases',
    type: 'github-releases',
    url: 'https://api.github.com/repos/vercel/next.js/releases',
    title: 'Next.js Releases',
  },
  {
    id: 'shadcn-releases',
    type: 'github-releases',
    url: 'https://api.github.com/repos/shadcn/ui/releases',
    title: 'shadcn/ui Releases',
  },
  {
    id: 'tauri-releases',
    type: 'github-releases',
    url: 'https://api.github.com/repos/tauri-apps/tauri/releases',
    title: 'Tauri Releases',
  },
  {
    id: 'prettier-releases',
    type: 'github-releases',
    url: 'https://api.github.com/repos/prettier/prettier/releases',
    title: 'Prettier Releases',
  },
];

export const rankingKeywords: string[] = [
  'typescript',
  'ts',
  'javascript',
  'react',
  'next.js',
  'vue',
  'svelte',
  'angular',
  'edge',
  'nuxt',
  'astro',
  'sveltekit',
  'remix',
  'prisma',
  'prisma-client',
  'prisma-orm',
  'node',
  'bun',
  'vite',
  'webpack',
  'deno',
  'edge',
  'performance',
  'release',
  'rc',
  'beta',
  'deprecation',
  'migration',
  'security',
  'nextjs',
  'remix',
  'astro',
  'solidjs',
  'qwik',
  'preact',
  'lit',
  'stimulus',
  'alpinejs',
  'fresh',
  'esbuild',
  'rollup',
  'parcel',
  'nx',
  'turborepo',
  'vitepress',
  'storybook',
  'eslint',
  'prettier',
  'pnpm',
  'yarn',
  'npm',
  'zod',
  'tRPC',
  'graphql',
  'urql',
  'apollo',
  'jest',
  'vitest',
  'playwright',
  'cypress',
  'vercel',
  'netlify',
  'supabase',
  'planetscale',
  'firebase',
  'cloudflare',
  'aws',
  'lambda',
  'edge functions',
  'serverless',
  'dx',
  'cli',
  'refactor',
  'debugging',
  'monitoring',
  'telemetry',
  'observability',
  'devtools',
  'test coverage',
  'webassembly',
  'wasm',
  'service worker',
  'pwa',
  'hydration',
  'partial hydration',
  'lazy loading',
  'rendering',
  'streaming',
  'compiler',
  'build time',
  'runtime',
  'lighthouse',
  'open source',
  'community',
  'release candidate',
  'breaking change',
  'bugfix',
  'feature flag',
  'experimental',
  'deprecated',
  'security patch',
];
