name: CI

on:
  push:
    branches: [ main, scaffold ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: Install
        run: bun install
      - name: Typecheck
        run: bun x tsc --noEmit
      - name: Lint
        run: bun x eslint . --ext .ts,.tsx --max-warnings=0
      - name: Test
        run: bun test --coverage
